### ISSUE TITLE
Cell 141-142: Figure not saving to PDF??

### ISSUE THREAD

**Issue by Cnblackwell** [Cnblackwell/TeamDragonParsers#11]
Hi everyone:

Please see 
![Screenshot 2024-02-18 at 12 13 54 AM](https://github.com/Cnblackwell/TeamDragonParsers/assets/156455477/c81fb60d-b059-4d53-a2e0-b7b1783858b1)
Cell 141-142: Figure not saving to PDF?? Can anyone please confirm or is it just my computer (Mac). Thanks!

Calen

**Comment by Delphin-Rajasekhar** [comment]
These are the recent files that are saved.
![image](https://github.com/Cnblackwell/TeamDragonParsers/assets/156693649/84dae53d-eecb-406e-9fd7-c0e5348ace3c)

**Comment by Delphin-Rajasekhar** [comment]
Fixing this @Cnblackwell

**Comment by Delphin-Rajasekhar** [comment]
Please check the code. I fixed it. @Cnblackwell 
Verify and close this issue.

**Comment by Delphin-Rajasekhar** [comment]
Fixed the .ipynb code. However, the codes in the Python script are not working fine. 
Team, please check this from a recent pull.
