### ISSUE TITLE
Graphs and YAML and outstandings.

### ISSUE THREAD

**Issue by Cnblackwell** [Cnblackwell/TeamDragonParsers#3]
Hello team well done working collaboratively today. 

The following require action by tomorrow, 4pm:

Here are the oustandings:
1.) YAML and final graphs (2 graphs)
2.) toml files with scripts
3.) test and debug as we complete with scripts and update README.md with instructions, installation, etc.
4.) Merge ‘debugging’ with ‘main’
5.) test: pip install git+repo url

**Comment by Delphin-Rajasekhar** [comment]
Assigned 1. YAML file @ChimaobiOsuegbu

**Comment by Delphin-Rajasekhar** [comment]
Assigned 1. Graphs finalisation @ynhi

**Comment by Cnblackwell** [comment]
Assigned graphs codes and ability yo save plots to @ynhi and @Delphin-Rajasekhar.

**Comment by Delphin-Rajasekhar** [comment]
Assigned toml files @Cnblackwell @Delphin-Rajasekhar

**Comment by Delphin-Rajasekhar** [comment]
Assigned - update README.md with instructions, installation, etc. @SidraBushra

**Comment by Cnblackwell** [comment]
Great job!

**Comment by SidraBushra** [comment]
Done
