### ISSUE TITLE
create a yaml file for job_config

### ISSUE THREAD

**Issue by Delphin-Rajasekhar** [Cnblackwell/TeamDragonParsers#4]
The recent codes haven't used yaml files. Upload a job configuration yaml file for a few variables.

**Comment by Cnblackwell** [comment]
Thank you @Delphin-Rajasekhar 
@ChimaobiOsuegbu is on it and we can review YAML execution tomorrow. Thanks everyone!

**Comment by Delphin-Rajasekhar** [comment]
Since exporting the .ipynb files does not give the exact code. So I'm fixing the issue now.
